theme: minima
title: "Siiri Kivim√§ki"
description: "Mathematician"

#url: "https://siirikivimaki.github.io"
#baseurl: ""

#plugins:
  #- jekyll-seo-tag

navigation:
  - title: Research
    url: /research
  - title: About
    url: /

