theme: minima
title: "Siiri Kivim√§ki"
description: "Mathematician"

plugins:
  - jekyll-seo-tag

navigation:
  - title: Research
    url: /research
  - title: About
    url: /

# Optional but recommended:
markdown: kramdown
highlighter: rouge
baseurl: ""       # leave empty for username.github.io
url: "https://siirikivimaki.github.io"

# Minima theme settings (optional)
minima:
  skin: classic
  social_links:
    github: siirikivimaki
